export const GESTURES = Object.freeze({
  HEAD_LEFT: 'HEAD_LEFT',
  HEAD_RIGHT: 'HEAD_RIGHT',
  HEAD_UP: 'HEAD_UP',
  HEAD_DOWN: 'HEAD_DOWN',
  EYES_CLOSED: 'EYES_CLOSED',
  MOUTH_OPEN: 'MOUTH_OPEN',
  TILT_LEFT: 'TILT_LEFT',
  TILT_RIGHT: 'TILT_RIGHT',
  NONE: 'NONE',
})
